version: '3.8'

services:
  app:
    image: openjdk:23
    container_name: fcoder-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ["java", "-jar", "app.jar"]
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: fcoder
    restart: always
    environment:
      POSTGRES_USER: fcoder
      POSTGRES_PASSWORD: fcoderpassword
      POSTGRES_DB: fcoder
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
