services:
  fcoder-forum-frontend:
    image: ${REGISTRY}/fcoder-forum-frontend:latest
    build:
      context: ../frontend
      dockerfile: Dockerfile

    profiles:
      - build
      - client

  # fcoder-forum-backend:
  #   image: ${REGISTRY}/fcoder-forum-backend:latest
  #   build:
  #     context: ../backend
  #     dockerfile: Dockerfile

  #   profiles:
  #     - build
  #     - server

  # fcoder-forum-ai:
  #   image: ${REGISTRY}/fcoder-forum-ai:latest
  #   build:
  #     context: ../ai
  #     dockerfile: Dockerfile

  #   profiles:
  #     - build
  #     - agent
