spring:
  application:
    name: Fcoder
  datasource:
    username: ${DB_USERNAME:fcoder}
    password: ${DB_PASSWORD:fcoderpassword}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fcoder_db}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST:localhost}
      timeout: 2000
      connect-timeout: 2000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:claimrequestsystem@gmail.com}
    password: ${MAIL_PASSWORD:ihss oorb exus dcph}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  profiles:
    active: ${SPRING_PROFILE:dev}

server:
  servlet:
    context-path: /api/v1
  port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true
    path: /swagger-ui
    url: /api-docs

base-urls:
  api: ${BASE_URL_API:null}
  front-end: ${FRONTEND_URL:null}
  origin-allows: ${ORIGIN_ALLOWED:""}
  root-host: ${ROOT_HOST:""}

access-token:
  max-age: ${ACCESS_TOKEN_EXT:86400000}
  secret-key: ${ACCESS_TOKEN_KEY:longAndComplexSecretKeyWithAtLeast64BytesOfRandomness}

refresh-token:
  max-age: ${REFRESH_TOKEN_EXT:315360000}
  secret-key: ${REFRESH_TOKEN_KEY:anotherLongAndComplexSecretKeyDifferentFromTheAccessTokenKey}

swagger-url: ${SWAGGER_URL:null}

oauth2:
  google:
    clientId: ${GOOGLE_CLIENT_ID}
    clientSecret: ${GOOGLE_CLIENT_SECRET}
    scopes:
      - email
      - profile
    redirectUrl: ${GOOGLE_REDIRECT_URL}
    userProfileEndpoint: ${GOOGLE_USERPROFILE_ENDPOINT}

payment:
  vnpay:
    tmnCode: YOUR_TMN_CODE
    secretKey: YOUR_SECRET_KEY
    returnUrl: https://yourdomain.com/payment/vnpay-return
    apiUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    version: "2.1.0"
    command: "pay"
    currencyCode: "VND"
    locale: "vn"
  callback: ${PAYMENT_CALLBACK:http://localhost:3000/checkout}

forgot-password:
  timeout: ${FORGOT_PASSWORD_TIMEOUT:10}
  callbackUrl: ${FORGOT_PASSWORD_CALLBACK:http://localhost:3000/forgot-password}
